### PR TITLE
Add fallback functionality for Client.API()

### LINKED ISSUE #67: Recent change to sendgrid/rest is breaking sendgrid/sendgrid-go
#### Issue Summary

Recent change to sendgrid/rest is breaking sendgrid/sendgrid-go. Ran
`go get github.com/sendgrid/sendgrid-go`

getting errors when building:
`../../vendor/github.com/sendgrid/sendgrid-go/sendgrid.go:49:2: not enough arguments to return`

`../../vendor/github.com/sendgrid/sendgrid-go/sendgrid.go:49:22: DefaultClient.API undefined (type *rest.Client has no field or method API)`

#### Steps to Reproduce

1. `go get github.com/sendgrid/sendgrid-go`
2. `go build`
3. errors

rest.Client.API function does not exist anymore and is still being used by sendgrid/sendgrid-go.

#### Technical details:

* package: github.com/sendgrid/sendgrid-go version: v3.4.1
* go version go1.9 darwin/amd64

### PR DESCRIPTION
**Pull request by jerbob92**
# Fixes # 
Fixes #67

### Checklist
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
-  While the recent change from #19 added fallback functionality for the global available API function, it did not add fallback functionality for the API function in the Client, breaking the Sendgrid Go client and possibly other implementations.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/rest?pullRequest=68) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/rest?pullRequest=68) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/rest?pullRequest=68) it.</sub>

**Comment by thinkingserious** [comment]
Hello @jerbob92,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by jerbob92** [comment]
@thinkingserious 
That's cool :)
I tried but after submitting the form I got the error message "I don't know who you are; I should, but regretfully I don't."

**Comment by thinkingserious** [comment]
Hi @jerbob92,

Please try the form again, I believe the error is fixed.

Thanks!

With Best Regards,

Elmer

**Comment by jerbob92** [comment]
@thinkingserious Yes, worked now. Thanks!

**Pull request merged**
