### PR TITLE
Add ability to use custom HTTP client.

### LINKED ISSUE #5: No way to set custom http.Client
Required for Google App Engine support, since a `urlfetch.Client` is used for HTTP requests.

### PR DESCRIPTION
**Pull request by broady**
Fixes #5.

### CODE REVIEW

**Comment by thinkingserious** [comment]
@broady awesome, thanks!

Please sign our CLA so I can merge: https://github.com/sendgrid/rest/blob/master/CONTRIBUTING.md#cla

**Comment by broady** [comment]
Thanks, I need our open source team to review the repo and CLA. I can't sign it on behalf of Google.

Hold tight!

**Comment by broady** [comment]
@thinkingserious I have some questions - what's your company e-mail address?

**Comment by thinkingserious** [comment]
Please send the email to dx@sendgrid.com. Thanks!

**Comment by broady** [comment]
Superseded by #9.

**Pull request closed without merging**
