### PR TITLE
Add copyright year unittest

### PR DESCRIPTION
**Pull request by tuckerrc**
Fix for issue #51

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/rest?pullRequest=54) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/rest?pullRequest=54) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/rest?pullRequest=54) it.</sub>

**Comment by mbernier** [comment]
Merged in updated license file to verify that the test passes.

**Comment by mbernier** [comment]
Looks like TravisCI had a hiccup - rerunning the build now.

**Comment by tuckerrc** [comment]
Looks like TravisCI may have hiccuped again.

**Comment by mbernier** [comment]
I think Travis is a bit overwhelmed by this month :)

**Comment by mrmuskrat** [comment]
Looks good to me. Travis is overwhelmed and has been experiencing issues lately.

**Comment by mbernier** [comment]
If you are interested, we would love the opportunity to talk to you about Hacktoberfest and our API libraries.

Our agenda would be: Explore what you liked and is there anything we can do to improve? 

You can grab a time [on my calendar](https://calendly.com/matt-bernier/30min) that works for you and we can have a chat on Google Hangout or Skype. If you prefer, you can email me using my GitHub username at my company’s domain.

Thank you so much,

Matt Bernier - @mbernier - SendGrid Developer Experience Product Manager
Elmer Thomas - @thinkingserious - SendGrid Developer Experience Engineer
@SendGrid

**Comment by thinkingserious** [comment]
Hello @tuckerrc,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
